### ISSUE TITLE
ProgrammingError at /api/v2/quickload

### ISSUE THREAD

**Issue by mjour** [bcgov/aries-vcr-client#19]
![image](https://user-images.githubusercontent.com/96822355/221072910-955dbcc0-0cd4-4bd3-b06c-12ddbfeebe7b.png)

**Comment by WadeBarnes** [comment]
@amanji, Have the [bcgov/aries-vcr](https://github.com/bcgov/aries-vcr) and [bcgov/orgbook-bc-client](https://github.com/bcgov/orgbook-bc-client) implementations drifted from this template repo?

**Comment by amanji** [comment]
No they shouldn't have. AFAIK the quickload endpoint hasn't been updated for a while now.

**Comment by amanji** [comment]
Sorry I should restate this, yes the client interface is different. OrgBook BC now uses a Vue implementation, however this template hasn't been changed. We made some changes to the API when redeveloping the new OrgBook site but the V2 endpoints should be the same, IIRC.

**Comment by WadeBarnes** [comment]
Confirmed.  I spun up a fresh instance of aries-vcr and aries-vcr-client, and the API call is working.

![image](https://user-images.githubusercontent.com/10504350/221218771-08176a16-a2fc-4214-8b07-3059da25472c.png)

So is the app.

![image](https://user-images.githubusercontent.com/10504350/221218886-301d580c-d5c4-4074-8e88-9a131cb6d561.png)

**Comment by WadeBarnes** [comment]
@mjour, Check to make sure the vcr-db is running.  You should see this list of containers:
```
$ docker ps
CONTAINER ID   IMAGE                   COMMAND                  CREATED         STATUS         PORTS                                                                                                         NAMES
4382367823ed   vcr-web                 "/docker-entrypoint.…"   3 minutes ago   Up 3 minutes   80/tcp, 0.0.0.0:8080->8080/tcp                                                                                vcr-web_vcr-web_1
019c8b1c667d   vcr-api                 "container-entrypoin…"   4 minutes ago   Up 4 minutes   0.0.0.0:3000->3000/tcp, 0.0.0.0:8081->8080/tcp                                                                vcr_vcr-api_1
19e6b19c05e8   vcr-agent               "/bin/bash -c 'curl …"   4 minutes ago   Up 4 minutes   0.0.0.0:8021->8021/tcp, 0.0.0.0:8023-8024->8023-8024/tcp                                                      vcr_vcr-agent_1
1af6e8d37c45   vcr-api                 "container-entrypoin…"   4 minutes ago   Up 4 minutes   8080/tcp                                                                                                      vcr_vcr-worker_2
9e8f0c888ba0   vcr-api                 "container-entrypoin…"   4 minutes ago   Up 4 minutes   8080/tcp                                                                                                      vcr_vcr-worker_1
d66d7af7136e   schema-spy              "/sbin/tini /bin/sh …"   4 minutes ago   Up 4 minutes   0.0.0.0:8082->8080/tcp                                                                                        vcr_schema-spy_1
f5a7284c74bd   echo-app                "sh ./start.sh"          4 minutes ago   Up 4 minutes   0.0.0.0:8000->8000/tcp                                                                                        vcr_echo-app_1
a5e93d5af489   vcr_wallet-db           "docker-entrypoint.s…"   4 minutes ago   Up 4 minutes   0.0.0.0:5433->5432/tcp                                                                                        vcr_wallet-db_1
70d92dacd62e   solr                    "docker-entrypoint.s…"   4 minutes ago   Up 4 minutes   0.0.0.0:8983->8983/tcp                                                                                        vcr_vcr-solr_1
69cfc2394493   rabbitmq:3-management   "docker-entrypoint.s…"   4 minutes ago   Up 4 minutes   4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   vcr_rabbitmq_1
7bb469f67c73   vcr_vcr-db              "docker-entrypoint.s…"   4 minutes ago   Up 4 minutes   0.0.0.0:5432->5432/tcp                                                                                        vcr_vcr-db_1
```

**Comment by mjour** [comment]
@WadeBarnes 
The vcr-db is running.
`$ docker ps
CONTAINER ID   IMAGE                   COMMAND                  CREATED        STATUS        PORTS                                                                                                         NAMES
cd73a0189f3f   vcr-web                 "/docker-entrypoint.…"   15 hours ago   Up 15 hours   80/tcp, 0.0.0.0:8080->8080/tcp                                                                                vcr-web-vcr-web-1
5ff916a8b97f   vcr-api                 "container-entrypoin…"   15 hours ago   Up 15 hours   0.0.0.0:3000->3000/tcp, 0.0.0.0:8081->8080/tcp                                                                vcr-vcr-api-1
e8e8aed7d26b   vcr-agent               "/bin/bash -c 'curl …"   15 hours ago   Up 13 hours   0.0.0.0:8021->8021/tcp, 0.0.0.0:8023-8024->8023-8024/tcp                                                      vcr-vcr-agent-1
7a590eecd31e   vcr-api                 "container-entrypoin…"   15 hours ago   Up 15 hours   8080/tcp                                                                                                      vcr-vcr-worker-2
6b8deb6f4cd8   vcr-api                 "container-entrypoin…"   15 hours ago   Up 15 hours   8080/tcp                                                                                                      vcr-vcr-worker-1
d606f048d343   rabbitmq:3-management   "docker-entrypoint.s…"   15 hours ago   Up 15 hours   4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   vcr-rabbitmq-1
e872cb178d8c   solr                    "docker-entrypoint.s…"   15 hours ago   Up 15 hours   0.0.0.0:8983->8983/tcp                                                                                        vcr-vcr-solr-1
b35ea4d19188   echo-app                "sh ./start.sh"          15 hours ago   Up 15 hours   0.0.0.0:8000->8000/tcp                                                                                        vcr-echo-app-1
8cd590738dc1   vcr-vcr-db              "docker-entrypoint.s…"   15 hours ago   Up 15 hours   0.0.0.0:5432->5432/tcp                                                                                        vcr-vcr-db-1
9325d7b65174   vcr-wallet-db           "docker-entrypoint.s…"   15 hours ago   Up 15 hours   0.0.0.0:5433->5432/tcp                                                                                        vcr-wallet-db-1
bb3863ea51bf   von-network-base        "./scripts/start_nod…"   15 hours ago   Up 15 hours   0.0.0.0:9703-9704->9703-9704/tcp                                                                              von-node2-1
ccb70a5ed29c   von-network-base        "bash -c 'sleep 10 &…"   15 hours ago   Up 15 hours   0.0.0.0:9000->8000/tcp                                                                                        von-webserver-1
423aa4f79eab   von-network-base        "./scripts/start_nod…"   15 hours ago   Up 15 hours   0.0.0.0:9707-9708->9707-9708/tcp                                                                              von-node4-1
a4d84a5df994   von-network-base        "./scripts/start_nod…"   15 hours ago   Up 15 hours   0.0.0.0:9705-9706->9705-9706/tcp                                                                              von-node3-1
1d319bacea2e   von-network-base        "./scripts/start_nod…"   15 hours ago   Up 15 hours   0.0.0.0:9701-9702->9701-9702/tcp                                                                              von-node1-1
`

**Comment by WadeBarnes** [comment]
Try resetting aries-vcr as suggested in Discord; `./manage down`, `./manage start`.

**Comment by mjour** [comment]
./manage start seed=my_unique_seed_00000000000000000
or 
./manage start ?
How to get my_unique_seed_00000000000000000?

**Comment by WadeBarnes** [comment]
Based on the code in the `./manage` script it looks like:
`./manage start INDY_WALLET_SEED=gmogshd0000000000000000000000000`

But try getting everything to run using the defaults, `./manage start`, to start with.
